### ISSUE TITLE
Issue with decodeOpaqueId and product slugs

### ISSUE THREAD

**Issue by abennani15** [reactioncommerce/api-utils#77]
Issue : Decoding following product slug : "congelateur-midea-hs-186cn-copy" gives the error : ID namespace must be reaction/catalogItem

The Buffer.toString using utf8 returns a string containing `:` and thus gives namespace a weird value.
To fast check : https://stackblitz.com/edit/node-21kuap

Removing the "186" seems to fix it.

**Comment by janus-reith** [comment]
**Edit: Bug is reproducible, see below.**

Hi @abennani15, the error message is very precise here:
"congelateur-midea-hs-186cn-copy" is neither a product id, nor is it encoded.

An Internal Id would for example be: "BCTMZ6HTxFSppJESk", which would then be prefixed with the namespace "reaction/catalogItem" and the whole string would then be base64 encoded - That would be an encoded Id which could then be decoded. Above you have product slug which is not meant to be decoded.

For demo purposes, although not an _id that would ever be generated using the current way random id generation works, let's continue with "congelateur-midea-hs-186cn-copy":

Prefixing with the namespace, that would become:
"reaction/catalogItem:congelateur-midea-hs-186cn-copy"

Base64-Encoding it, you would get the following external Id:
cmVhY3Rpb24vY2F0YWxvZ0l0ZW06Y29uZ2VsYXRldXItbWlkZWEtaHMtMTg2Y24tY29weQ==

This could be encoded properly now, and return the internal value "congelateur-midea-hs-186cn-copy".

A more common example you might see would be something like:
"reaction/catalogItem:BCTMZ6HTxFSppJESk" which would turn into "cmVhY3Rpb24vY2F0YWxvZ0l0ZW06QkNUTVo2SFR4RlNwcEpFU2s="

**Comment by abennani15** [comment]
Hello, 
This happens when accessing a product page on storefront, using the slug.

**Comment by janus-reith** [comment]
Hi @abennani15, I'm able to reproduce this and understand what you mean now.

The nodejs webcontainer in blitz somehow didnt boot for me, so I created another example:
https://stackblitz.com/edit/graphql-2pn4jb?file=index.js

Actually, it looks like indeed just the sequence "186" is enough to cause decoding to fail, which is rather severe since it could come up in a valid internal Id aswell, e.g. : BCTMZ186xFSppJESk
I wonder which other sequences might be interpreted wrong aswell

@Akarshit

**Comment by abennani15** [comment]
Hi again, 
There is the slug "ed-32p-smart-full-hd-led32s60a" that fires the same bug, trying to figure out the sequence.

**Comment by janus-reith** [comment]
> ed-32p-smart-full-hd-led32s60a

Interesting, I could subsitute it down to this:
"--------------------------s60-"

Removing the length by one "-" char, changing the "s" to e.g. "a", or transposing the sequence by one char to e.g. "-------------------------s60--" would make it work again.
Really curious what's the explanation for this, researching now.

Another note: happens to s61-s69 aswell, but not to s59 or s70. These seem to be interpreted as ":" char.

**Comment by abennani15** [comment]
The sequence is interpreted as an UTF8 code, if you change .toString('hex') or base64 it works.
I think the decodeCatalogItemOpaqueId(slugOrId); on catalogItemProduct Query resolver should not be used since it receives only a slug.
I'll look where this query is used to confirm that.

**Comment by janus-reith** [comment]
@abennani15 The chain of how it is called is this:

Query resolver expects this to return either the decoded id or else fallback to the input value(in case of a slug):
https://github.com/reactioncommerce/api-plugin-catalogs/blob/27d02e3519f9517a3593d6a7357028a196719ee8/src/resolvers/Query/catalogItemProduct.js#L18

Function which passed along the input value with namespace is defined here: https://github.com/reactioncommerce/api-plugin-catalogs/blob/27d02e3519f9517a3593d6a7357028a196719ee8/src/xforms/id.js#L10

Actual decoding function is defined here: https://github.com/reactioncommerce/api-utils/blob/26ab4ff36722d521af2088c38f647ca31d30f750/lib/decodeOpaqueIdForNamespace.js#L16

The culprit then is here: https://github.com/reactioncommerce/api-utils/blob/26ab4ff36722d521af2088c38f647ca31d30f750/lib/decodeOpaqueId.js#L15
The string can be split, so both namespace and id are considered to exist and are returned.

One option as you say would be to separate these, so slugs have a separate query and decoding an id is not even attempted.
We do however have other usecases of these, so we should definitely fix the underlying issue of `decodeOpaqueId` not interpreting these sequences wrong.

**Comment by abennani15** [comment]
Or maybe add a isSlug true/false to the query to decide whether we use `decodeOpaqueId` or not ?

**Comment by janus-reith** [comment]
Considering how that our current internal Id length is currently fixed length, a quick fix that comes to mind might be to check length of the resolved id here to be 17 chars: https://github.com/reactioncommerce/api-utils/blob/26ab4ff36722d521af2088c38f647ca31d30f750/lib/decodeOpaqueId.js#L17
`if (namespace && id && id.length === 17)`

A better option would certainly be to not rely on any fixed id length, I wonder what better options we have.

There is this check: https://github.com/reactioncommerce/api-utils/blob/26ab4ff36722d521af2088c38f647ca31d30f750/lib/decodeOpaqueIdForNamespace.js#L20
One option might be to decide per usecase, wether this should result in an error or fallback to the input id aswell instead.

If this catalog query is the only case where we expect either an Id or slug this might be a bit less severe, still we really need to reconsider this construct thoroughly especially since the restriction was lifted for graphql input ids to always be encoded and internal Ids are accepted aswell.

**Comment by janus-reith** [comment]
Using an input value like "BCTMZ186xFSppJESk", I wonder how and if we could detect that besides the detected char ":", the rest of the string is not valid, although technically it is valid base64.

With "BCTMZ186xFSppJESk" we would receive:
namespace: $g_
id: T

It would be rather simple here to check for alphanumerical strings only, and else assume no namespace was given and fall back to `namespace: null` in `decodeOpaqueId`, causing `decodeOpaqueIdForNamespace` to also not compare the namespace then.
I do however wonder what the stakes are, that a wrongly-interpreted string which is not meant to be read as base64-encoded input would have the sequence that decodes to ":", but otherwise alphanumerical chars only - If that is a possibility, this would not work out.

**Comment by janus-reith** [comment]
@aldeed I think you've been the last one working on this when adding support for internal Ids with GraphQL last year, would really appreciate your input, maybe you have an idea how to solve this best?

**Comment by abennani15** [comment]
Maybe on Buffer.split we shouldn't set to 2, and check if the length is > 2 then first is namespace and remaining parts are the actual id ?

**Comment by aldeed** [comment]
It's been a while since I thought about this, but I believe it was done this way because the storefront client often won't know whether it's a slug or an ID in the URL, so rather than making them figure it out, the API just tries to figure it out. You could deprecate the GQL field and have two separate fields, but then that's just pushing the logic to the client where it's less likely to be implemented correctly.

The best solution I can think of to keep the current behavior is:
- GQL schema stays the same
- In the resolver, catch any error due to malformed ID, and fall back to assuming it's a slug (pass in unchanged as `catalogIdOrProductSlug`)
- Maybe in the fallback, test whether it's base64, and if so, throw the error as usual (in case it actually is an ID but with the wrong namespace
- Probably also be smarter about the logic in `decodeOpaqueId` as others have mentioned. I think it assumes alphanumeric ID, but there's probably no good reason to ignore colons in the ID, so it makes sense to read forward to the first colon to get namespace, and then assume everything after that is ID, even if there is a colon character. And then also throwing if no colon is found.
- It's also possible to do `Buffer.isEncoding('base64')` somewhere, and maybe that would be wise. But there should be some thought about whether it should throw or just skip decoding in that case. I think to skip decoding silently would be in some cases useful but could be a breaking change in other cases. Not sure.

**Comment by janus-reith** [comment]
Thanks for your input on this @aldeed!

> * Maybe in the fallback, test whether it's base64, and if so, throw the error as usual (in case it actually is an ID but with the wrong namespace

That was the main issue I was trying to figure out: Technically, something like the example "BCTMZ186xFSppJESk" could be read as valid base64. Some validators might complain it's not a multiple of 4 chars so that might be a hint, but then again something like "BCTMZ186xFSppJESkabc" might be, if we consider a solution that works for arbitrary Ids and not just our default ones.

The alphanumerical check I had in mind earlier might also not work out:
E.g. "YTJkMWRhcTpxM3EzcQ" <- This looks like and also could be a perfectly valid internal id (except that it's 18 chars instead of our default of 17).
It is however also valid base64, and decoding it would result in: "a2d1daq:q3q3q".
We have the colon in the middle, resulting in both namespace and id being read, and both the string before and after it would still be valid alphanumerical strings.

By now I'm thinking if we should maybe initialize `decodeOpaqueId` in some way and pass all registered namespaces there, ignoring any other potentially found ones. Or as proposed, don't throw an error and only explicitly look for a namespace that was also passed in with the function call. This would however also alter the behavior, as the "ID namespace must be ..."-Error would not be thrown anymore for false-positives.
Maybe we could also narrow it down enough by requiring the "reaction/" part as prefix for a namespace, and else not consider something a namespace. The error would only show up and might be helpful then in case you put in a wrong namespace, e.g. "catalogItem" instead of "catalogProduct".

**Comment by aldeed** [comment]
@janus-reith I see. Yes maybe passing a list of valid namespaces, or at least passing down the one expected namespace, is the only solution. I'm not sure it's technically necessary to check this in `decodeOpaqueId`, though. If it believes the namespace to be `a2d1daq`, that is okay and the outer function will throw the error because it does not match. And then in this specific slugOrId scenario, that error can be caught and ignored. Unless I'm missing something. It's messy but I don't think there's any way to be foolproof since an ID can be almost anything and a slug can also be almost anything.
